### ISSUE TITLE
Improve HTTP request performance to Flair API

### ISSUE THREAD

**Issue by fcfort** [RobertD502/hass-flair-helper#6]
I've noticed in practice that HTTP requests to the Flair API often results in timeouts in Home Assistant. The HTTP performance of this package could be improved by making an upstream change to the public Flair python API client. I've filed https://github.com/flair-systems/flair-api-client-py/issues/6 against that project but it doesn't seem like the maintainers are very active.

What do you think of a change like this and would you consider forking `flair-systems/flair-api-client-py` if it can't be fixed upstream?

**Comment by RobertD502** [comment]
I completely agree with you about the performance. I have a PR that has been in limbo there so I doubt a new one would get pushed through. The current plan, when I get some more time, is to create a new asynchronous library that'll use aiohttp, OAuth2, and completely cut out their API wrapper.

**Comment by fcfort** [comment]
Would you be willing to use in this project some new fork of `flair-api-client-py`, maybe called something like `hass-flair-api-client`? I'd like to just fork their project, add support for connection pooling, test it w/ Home Assistant and use it in this project as a drop-in replacement. You can own the repo / be a `CODEOWNER` / etc. if you'd like.

**Comment by RobertD502** [comment]
Currently working on it on my local machine. Will fork it and add the changes after. Want to be sure nothing is broken before pushing it out to Home Assistant / other users.

**Comment by RobertD502** [comment]
Forked version can be found [here](https://github.com/RobertD502/flair-api-client-py/tree/hass-flair-api-client).

Just released Flair integration version `0.0.5.8` which uses the forked wrapper.

Thanks for bringing this to my attention!
